#use for base image
FROM ubuntu 
# who maintain that image (optional)
MAINTAINER akash 
# running command through the shell 
RUN apt update ; apt install vim ncal iputils-ping -y
RUN mkdir Akash A B C 

